codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

comment:
  layout: "reach, diff, flags, files"
  behavior: new
  require_changes: true

ignore:
  - "src/test/**"
  - "src/config/**"
  - "src/**/*.module.ts"
  - "src/**/*.spec.ts"
  - "src/main.ts"
  - "src/**/index.ts"
  - "src/graphql/graphql.types.ts"
